# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 09:18
from __future__ import unicode_literals

import default_documents.validators
from django.db import migrations, models
import metadata.fields


class Migration(migrations.Migration):

    dependencies = [
        ('default_documents', '0062_auto_20160630_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordeliverable',
            name='discipline',
            field=metadata.fields.ConfigurableChoiceField(default='PCS', list_index='DISCIPLINES', max_length=3, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='contractordeliverable',
            name='document_type',
            field=metadata.fields.ConfigurableChoiceField(default='PID', list_index='DOCUMENT_TYPES', max_length=3, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='contractordeliverable',
            name='sequential_number',
            field=models.CharField(default='0001', help_text='Select a four digit number', max_length=4, validators=[default_documents.validators.StringNumberValidator(4)], verbose_name='sequential Number'),
        ),
        migrations.AlterField(
            model_name='contractordeliverable',
            name='system',
            field=metadata.fields.ConfigurableChoiceField(blank=True, list_index='SYSTEMS', max_length=50, null=True, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='contractordeliverable',
            name='unit',
            field=metadata.fields.ConfigurableChoiceField(default='000', list_index='UNITS', max_length=3, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='contractordeliverable',
            name='wbs',
            field=metadata.fields.ConfigurableChoiceField(blank=True, list_index='WBS', max_length=20, null=True, verbose_name='WBS'),
        ),
        migrations.AlterField(
            model_name='contractordeliverablerevision',
            name='status',
            field=metadata.fields.ConfigurableChoiceField(blank=True, default='STD', list_index='STATUSES', max_length=3, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='addresses',
            field=metadata.fields.ConfigurableChoiceField(blank=True, list_index='ADDRESSES', max_length=50, null=True, verbose_name='Addresses'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='author',
            field=metadata.fields.ConfigurableChoiceField(blank=True, list_index='AUTHORS', max_length=250, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='document_type',
            field=metadata.fields.ConfigurableChoiceField(default='PID', list_index='DOCUMENT_TYPES', max_length=3, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='originator',
            field=metadata.fields.ConfigurableChoiceField(default='FWF', list_index='ORIGINATORS', max_length=3, verbose_name='Originator'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='recipient',
            field=metadata.fields.ConfigurableChoiceField(list_index='RECIPIENTS', max_length=50, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='sequential_number',
            field=models.CharField(default='0001', help_text='Type in a four digit number', max_length=4, validators=[default_documents.validators.StringNumberValidator(4)], verbose_name='sequential Number'),
        ),
        migrations.AlterField(
            model_name='correspondencerevision',
            name='status',
            field=metadata.fields.ConfigurableChoiceField(list_index='STATUS_COR_MOM', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='demometadatarevision',
            name='status',
            field=models.CharField(blank=True, choices=[('STD', 'Started'), ('IDC', 'Inter Discipline Check'), ('IFR', 'Issued For Review'), ('IFA', 'Issued For Approval'), ('IFD', 'Issued For Design'), ('IFC', 'Issued For Construction'), ('FIN', 'Final'), ('IFI', 'Issued For Information'), ('ASB', 'As Built'), ('CLD', 'Cancelled'), ('SPD', 'Superseded'), ('ANA', 'Analysis'), ('BAS', 'Design Basis')], default='STD', max_length=3, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='document_type',
            field=metadata.fields.ConfigurableChoiceField(default='PID', list_index='DOCUMENT_TYPES', max_length=3, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='originator',
            field=metadata.fields.ConfigurableChoiceField(default='FWF', list_index='ORIGINATORS', max_length=3, verbose_name='Originator'),
        ),
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='prepared_by',
            field=metadata.fields.ConfigurableChoiceField(blank=True, list_index='AUTHORS', max_length=250, null=True, verbose_name='Prepared by'),
        ),
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='recipient',
            field=metadata.fields.ConfigurableChoiceField(list_index='RECIPIENTS', max_length=50, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='minutesofmeeting',
            name='sequential_number',
            field=models.CharField(default='0001', help_text='Type in a four digit number', max_length=4, validators=[default_documents.validators.StringNumberValidator(4)], verbose_name='sequential Number'),
        ),
        migrations.AlterField(
            model_name='minutesofmeetingrevision',
            name='status',
            field=metadata.fields.ConfigurableChoiceField(list_index='STATUS_COR_MOM', max_length=20, verbose_name='Status'),
        ),
    ]
