# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 20:43
from __future__ import unicode_literals

from django.db import migrations
import privatemedia.storage
import transmittals.fields


class Migration(migrations.Migration):

    dependencies = [
        ('default_documents', '0063_auto_20170524_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractordeliverablerevision',
            name='client_comments',
            field=transmittals.fields.ClientCommentsFileField(blank=True, null=True, storage=privatemedia.storage.ProtectedStorage(), upload_to=transmittals.fields.client_comments_file_path, verbose_name='Client Comments'),
        ),
        migrations.AddField(
            model_name='gtgmetadatarevision',
            name='client_comments',
            field=transmittals.fields.ClientCommentsFileField(blank=True, null=True, storage=privatemedia.storage.ProtectedStorage(), upload_to=transmittals.fields.client_comments_file_path, verbose_name='Client Comments'),
        ),
    ]
