# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_documents', '0064_auto_20181125_2143'),
        ('transmittals', '0058_set_due_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractordeliverablerevision',
            name='external_review_due_date',
        ),
        migrations.RemoveField(
            model_name='contractordeliverablerevision',
            name='purpose_of_issue',
        ),
        migrations.RemoveField(
            model_name='gtgmetadatarevision',
            name='external_review_due_date',
        ),
        migrations.RemoveField(
            model_name='gtgmetadatarevision',
            name='purpose_of_issue',
        ),
    ]
