# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_documents', '0067_auto_20181213_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractordeliverablerevision',
            name='client_comments_detail',
            field=models.TextField(blank=True, verbose_name='Client comments detais'),
        ),
        migrations.AddField(
            model_name='gtgmetadatarevision',
            name='client_comments_detail',
            field=models.TextField(blank=True, verbose_name='Client comments detais'),
        ),
    ]
