# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 09:18
from __future__ import unicode_literals

import default_documents.validators
from django.db import migrations, models
import privatemedia.fields
import privatemedia.storage


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0055_auto_20160303_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportedrevision',
            name='comments',
            field=privatemedia.fields.ProtectedFileField(blank=True, null=True, storage=privatemedia.storage.ProtectedStorage(), upload_to='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='trsrevision',
            name='sequential_number',
            field=models.CharField(blank=True, default='0001', help_text='Select a four digit number', max_length=4, null=True, validators=[default_documents.validators.StringNumberValidator(4)], verbose_name='sequential Number'),
        ),
    ]
