# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 15:12
from __future__ import unicode_literals

from django.db import migrations
from transmittals.models import OutgoingTransmittal


def set_due_dates(apps, schema_editor):
    transmittals = OutgoingTransmittal.objects.all()

    for transmittal in transmittals:
        revision = transmittal.get_last_revisions()[0]
        transmittal.purpose_of_issue = revision.purpose_of_issue
        transmittal.external_review_due_date = revision.external_review_due_date
        transmittal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transmittals', '0057_auto_20181212_1537'),
    ]

    operations = [
        migrations.RunPython(set_due_dates)
    ]
