# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160322_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_behind_schedule_alert_mails',
            field=models.BooleanField(default=False, verbose_name='Send alerts when documents are behind schedule'),
        ),
    ]
